CREATE DATABASE nodelogin;


CREATE TABLE(
id BIGSERIAL PRIMARY KEY NOT NULL,
name VARCHAR(200) NOT NULL,
email VARCHAR(200) NOT NULL,
password VARCHAR(200) NOT NULL,
birthdate DATE NOT NULL,
country_id VARCHAR(255) NOT NULL,
UNIQUE (email)
);

CREATE TABLE country(
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL
);
